### ISSUE TITLE
On unscrollable page, login is stuck to bottom of screen outside of nav.

### ISSUE THREAD

**Issue by Ledivin** [PredixDev/px-login#1]
Because the page doesn't scroll and the navbar height is never changed, the 'sticky' class is never added.

Current workaround is that my content page fires 'nav-height-changed' on ready.

![image](https://cloud.githubusercontent.com/assets/129755/11908997/97540a32-a596-11e5-851e-4319d7baa29a.png)

**Comment by yashdoshi89** [comment]
Looks like an intermittent issue with old version. Cannot reproduce it.

**Comment by 212361828** [comment]
I was able to reproduce this by making sure the window had enough content to scrolldown, then scroll to the bottom. and adjust the height of the window until this happens.  As @Ledivin points out the '.sticky' class is not applied and thus the position is set to fixed instead of absolute.
