### ISSUE TITLE
px-login#bundle overflows into footer

### ISSUE THREAD

**Issue by perryjsteward** [PredixDev/px-login#12]

**Comment by gedesigntech** [comment]
hi @perrah thanks for the fix to this issue of px-login. There are other items in our list for px-login, and we are looking into addressing all of them in possibly a major re-work of the component. Please stay tuned for updates.

**Comment by randyaskin** [comment]
Per Henry's comments, Greg completely rebuilt the component. I don't think this is still a valid issue with later versions.
