### ISSUE TITLE
Long usernames overflow outside of px-app-nav

### ISSUE THREAD

**Issue by chronicIntrovert** [PredixDev/px-login#15]
## Expected behavior and actual behavior:

The username should be truncated if it is longer than the width of px-app-nav, but is currently overflowing past the nav sidebar.
## Steps to reproduce the problem:

Have a really long username
## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

Component version: 0.5.0
Browser: Chrome 53
OS: MacOS El Capitan
## Screenshots (_optional, but very helpful_):

<img width="291" alt="screen shot 2016-10-14 at 3 17 34 am" src="https://cloud.githubusercontent.com/assets/4204797/19384232/1cc0a21c-91bd-11e6-84c2-3492e187f358.png">

**Comment by randyaskin** [comment]
Duplicate / no longer an issue post-1.0 refactor.
