### ISSUE TITLE
The logged in user name text that comes after loging in overlapws with the left hand navigation menu when the size of the screen is decreased vertically, by pressing f12

### ISSUE THREAD

**Issue by mihir-pathak-git** [PredixDev/px-login#17]
# Submit an Issue
![px-login-alignment-issue](https://cloud.githubusercontent.com/assets/23211073/19924351/9297e474-a111-11e6-9b55-3ec120a8e94f.png)

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

**Comment by randyaskin** [comment]
I believe this was mitigated by the v1 refactoring that Greg completed.
