### ISSUE TITLE
Control does not operate as visual design indicates

### ISSUE THREAD

**Issue by dalejoel** [PredixDev/px-login#18]
# Submit an Issue

## Expected behavior and actual behavior:
I expect to click on the ^ symbol next to the user name to bring up a menu of options, including "Sign Out." Then, after interacting with the subsequent menu or mousing out of the menu box, I expect that menu to go away.

Actual -
The menu always exists, and any hover event in the completely transparent menu area will cause it to become opaque. This is a problem because sometimes the navigation items overlap with the sign out menu and moving the mouse over that nav item causes the sign out menu to appear instead; this makes it impossible to interact with the bottom most nav item. Having the menu only pop up when interacting with the ^ symbol, would solve this problem from a usability standpoint.

## Steps to reproduce the problem:
Have enough navigation menu items that the size of your window forces the user name to be just below the navigation menu items. Then move the mouse down from the top of the screen to try and select the bottom nav item. You'll see the "Sign Out" control light up and cover your nav screen instead with no way to stop it.

## Environment: 
px-input v.6 
Chrome Version 54.0.2840.99 m   Also happens on firefox
Windows 7

## Screenshots
![signoutgood](https://cloud.githubusercontent.com/assets/17937939/21372912/36b1522e-c6cf-11e6-8258-9503525040af.PNG)
![signoutbad](https://cloud.githubusercontent.com/assets/17937939/21372916/39bf42d2-c6cf-11e6-9865-1c60d6a5fb2d.PNG)

**Comment by randyaskin** [comment]
As of v1.0.0 of px-login, the popover appears on click rather than hover, so I think this issue is mitigated.
