### ISSUE TITLE
Logged In user's display name : Option to display specific field from userInfo

### ISSUE THREAD

**Issue by ezhilvendhan** [PredixDev/px-login#25]
Can we have an option to display a field from userInfo object, instead of displaying user_name (from userInfo response) / userName(input)?

Eg:
````
<px-login
  logged-in-display-name-field="given_name">
</px-login>
````

Use case: Consider an SSO authentication which returns the SSO Id in the user_name response field. We got a specific use case where we need to display the given_name instead. 

Would like to submit my pull request once this is approved.

**Comment by randyaskin** [comment]
Added in v2.2.7. Sorry for the long turnaround, but I've heard this request a few more times recently, so bumped priority.
