### ISSUE TITLE
fetch-user-info-on-load can't be set to false via markup

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-login#26]
## Expected behavior and actual behavior:

`<px-login fetch-user-info-on-load="false"></px-login>` should not request any data.
however it keeps calling GET /userinfo.

IMO the issue is the default value of the property: 

> For a Boolean property to be configurable from markup, it must default to false. If it defaults to true, you cannot set it to false from markup, since the presence of the attribute, with or without a value, equates to true [see docs](https://www.polymer-project.org/1.0/docs/devguide/properties).

## Steps to reproduce the problem:

`<px-login fetch-user-info-on-load="false"></px-login>`

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

v2.0.0

**Comment by nonmetalhail** [comment]
You're right. Looks like there at several properties on this component that do this. We'll have to look into how was want to fix this.

In the meantime, you can bind it to a property and set that to false to force it to work

**Comment by nonmetalhail** [comment]
Ok, flipped the prop and logic in the redesign branch
