### ISSUE TITLE
Popover is in wrong location

### ISSUE THREAD

**Issue by moreaumc** [PredixDev/px-login#27]
# Submit an Issue

Hi,

Thanks for helping us improve the Predix UI platform by submitting an issue.

Before you begin, please check the list of existing issues to avoid submitting a duplicate issue.

To help us solve this issue as fast as possible, please fill out the following sections:

## Expected behavior and actual behavior:

When clicking on the log in component in the demo, the popover is not aligned. It should be centered with the component, based on the popover location.

## Steps to reproduce the problem:

For the demo, enter a username and click on the login item. The popover will not be aligned.

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

v2.0.6, Chrome Version 60.0.3112.101, Mac OS Sierra 10.12.3

## Screenshots (_optional, but very helpful_):

![screen shot 2017-08-18 at 9 15 16 am](https://user-images.githubusercontent.com/7944940/29467598-e5cc492e-83f5-11e7-90b9-1198f952ab29.png)

## Code examples help us better understand the issue - follow the appropriate codepen for the component by going to https://predix-ui.com, finding the component in question, and clicking on the pencil icon under the demo.
        Once you've created your code example, you can save it under a new url.
        Please note that you should NOT use the same methods for production as the ones used in codepen - these methods are not production ready.

You can see the behavior in the demo.

**Comment by randyaskin** [comment]
Fixed in v2.0.4 of popover. Should reflect in login and the website after they rebuild.
