### ISSUE TITLE
PX-LOGIN session handling

### ISSUE THREAD

**Issue by chakrabortyarpan29** [PredixDev/px-login#3]
I am unable to handle and manage the session from PX_LOGIN. How can we access the user info from Angular JS controllers and manage accordingly.

**Comment by mdwragg** [comment]
We need more information to answer your question, what are you trying to do?

**Comment by btmurrell** [comment]
hey @mdwragg , see #7 -- i faced the same issue when dealing with server-side system stability.

**Comment by randyaskin** [comment]
I believe this is leftover from the previous implementation of login. Closing.
