### ISSUE TITLE
Clicking "Sign In" on the demo redirects to homepage

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-login#30]
## Expected behavior and actual behavior:
Expected: When I click "Sign In" something happens to indicate that it is working, but I stay on the demo page
Actual: When I click "Sign In" I am redirected to the home page with an error message 

## Steps to reproduce the problem:
Click "Sign In" on the px-login demo page

## Screenshots (_optional, but very helpful_):

![screen shot 2017-09-27 at 11 13 25 am](https://user-images.githubusercontent.com/9092541/30930051-4b1092ec-a375-11e7-9550-a20509386645.png)

**Comment by randyaskin** [comment]
I've noticed this before too, something to do with the relative paths. It works differently in the standalone than it does in the site, but I think you can "fix it" (fake it) by supplying a value for the user name property instead of having it look in the .json file for one.
