### ISSUE TITLE
Not compatible with IE11

### ISSUE THREAD

**Issue by AnirbanKundu** [PredixDev/px-login#5]
px-login not compatible with IE11. Was trying to use the latest version of px-login and getting the following exception -

{ABORT_ERR: 20, code: 3, constructor: DOMException {...}, DATA_CLONE_ERR: 25, DOMSTRING_SIZE_ERR: 2, HIERARCHY_REQUEST_ERR: 3, INDEX_SIZE_ERR: 1, INUSE_ATTRIBUTE_ERR: 10, INVALID_ACCESS_ERR: 15, INVALID_CHARACTER_ERR: 5, INVALID_MODIFICATION_ERR: 13, INVALID_NODE_TYPE_ERR: 24, INVALID_STATE_ERR: 11, message: "HierarchyRe...", name: "HierarchyRe...", NAMESPACE_ERR: 14, NETWORK_ERR: 19, NO_DATA_ALLOWED_ERR: 6, NO_MODIFICATION_ALLOWED_ERR: 7, NOT_FOUND_ERR: 8, NOT_SUPPORTED_ERR: 9 ...}

Please suggest .

**Comment by carlosfhernandez** [comment]
Thanks for feedback. Could you please supply us with the following:
1. Version you are using
2. Version of Polymer you are using
3. If you are using this within the Dashboard Seed _Starter Pack_, could you send us the version of that as well?
4. If you are using Angular, version
5. Possible location where we can look at this issue
6. Data or service endpoint that you are using, if possible
7. Does this work in isolation outside of your app? 

Thank you -- any of these would greatly help.

**Comment by mdwragg** [comment]
Hi, I've just tested this in IE11 and IE10 in the production seed and local seed and all works as expected.

Closing this issue as there appears to be a parallel discussion via email. Thanks.
