### ISSUE TITLE
/userinfo error is not forwarded in case of error response

### ISSUE THREAD

**Issue by btmurrell** [PredixDev/px-login#7]
in the case where /userinfo does not receive 200 response, the promise is rejected with no parameter.  the reject() function should pass the repsponse object so that the developer can consume to determine the error.

this causes a problem when session store is down (as reported in   #3) -- in my case, if i have no session (redis died) /userinfo returns a 503 with response body.  my handler for getUserInfo() needs to know response body in reject.  

See PR #6 for fix.

**Comment by mdwragg** [comment]
@ek - one for you, I know you're an expert in all things px-login now!

**Comment by nonmetalhail** [comment]
@carlosfhernandez Can you please create a rally story for this?

**Comment by btmurrell** [comment]
@mdwragg @carlosfhernandez  bump

**Comment by btmurrell** [comment]
@mdwragg @carlosfhernandez @nonmetalhail  bump

**Comment by kentcabarle** [comment]
Can you add a custom event every time the px-login successfully obtains the userInfo upon page load?

**Comment by randyaskin** [comment]
This is based on the previous implementation of px-login before Greg rebuilt it. New implementation no longer uses promises, but I did add a console log in v2.0.1 if the iron-ajax request receives an error instead of a response. Going to close this and the associated PR.
