### ISSUE TITLE
px-login overflows into footer

### ISSUE THREAD

**Issue by drunkplato** [PredixDev/px-login#9]
<img width="268" alt="screen shot 2016-05-25 at 2 36 25 pm" src="https://cloud.githubusercontent.com/assets/6413077/15557132/353bca2a-2286-11e6-938e-d56dc92a573a.png">
This occurs when you have an expanding container push the px-login element off of the page and then collapse the expanding container. Trying to figure out a way to solve this issue.

**Comment by 212361828** [comment]
We had this issue as well.  Long story short, there is a media query changing the position from absolute to fixed at the wrong time.  

I'm sure this was put in there for a reason but not sure what it was.  Maybe the idea is to keep it pinned when app nav changes to one of it's many states.  Not sure but keeping it absolute is working for our needs.

**Comment by randyaskin** [comment]
I don't believe this still applies in recent versions of the component (especially after Greg rebuilt it).
